### ISSUE TITLE
Empty `MachinePool` configs when creating a new cluster when the Elemental UI extension is installed.

### ISSUE THREAD

**Issue by David-VTUK** [rancher/elemental-ui#95] opened 2023-04-13 14:24 UTC
**Setup**
- Rancher version: 2.7.2 (Prime) Upgraded from 2.7.1 (Prime)
- Browser type & version: Firefox 112.0

**Describe the bug**
After upgrading a Rancher Prime install from 2.7.1 to 2.7.2 and attempting to create a new cluster on an IaaS provider (EC2/vSphere), `machinePools` element is empty.

**To Reproduce**

1. Upgrade a Rancher Prime instance from 2.7.1 to 2.7.2
2. Attempt to create an RKE2/K3s cluster on a Infrastructure provider like EC2 or vSphere

**Result**
Machine pools are empty and cannot be configured
![image](https://user-images.githubusercontent.com/5892615/231788497-f449ed97-0566-4163-a83a-0e83a0e8df9d.png)

**Expected Result**
Machine pool configuration to be present

**Screenshots**

**Additional context**
Attached HAR file

[2.7.2-ui-error.zip](https://github.com/rancher/dashboard/files/11223141/2.7.2-ui-error.zip)

**Comment by gaktive** [comment] 2023-04-13 22:40
Upon discussion with @pgonin, this ticket is over to the Elemental UI team to investigate.

**Comment by aalves08** [comment] 2023-04-14 08:11
Good morning all.

There were issues already noted on the cluster provisioning part due to some conflicts between files that are on Elemental UI (up until v1.1.0 included) which were wrongly overwriting files from Rancher Dashboard.

looking into the HAR file, you are using `v1.0.0`: https://rancher.virtualthoughts.co.uk/api/v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-operator:80/proxy/elemental/1.0.0/plugin/elemental-1.0.0.umd.min.js

Which means that all of the problems are still not fixed on the Elemental UI side. The fix for this problem on cluster provisioning was a 2 part fix:
- 1st part was in Dashboard (which will come in `2.7.2`)
- other was in Elemental UI (which comes with `v1.1.0` - to be released on the following days)

So, all problems should be fixed with the combo of Dashboard `v2.7.2` + Elemental UI `v1.1.0` (upcoming release).

So, unfortunately, the reported issue is still an expected behaviour.

Shall we keep this issue open until we can test the combo of Dashboard `v2.7.2` + Elemental UI `v1.1.0`, or just close it?

@agracey @gaktive @juadk @David-VTUK

**Comment by David-VTUK** [comment] 2023-04-14 08:34
Thanks for the detailed feedback @aalves08.

We shouldn't be shipping UI Extensions that knowingly break core functionality.

**Comment by pgonin** [comment] 2023-04-14 12:51
There are 2 possible workarounds:
- remove elemental-ui if you don't need elemental and need provisioning to work on 2.7.2
- install Staging version of Elemental 1.1 if you need Elemental
Situation will be fully fixed with release of Elemental in coming days

**Comment by aalves08** [comment] 2023-11-15 16:06
@David-VTUK I believe this should be fixed by now - version `1.2.0` of Elemental extension + a recent backend version of rancher. Can you confirm? If so, we can close this.

(doing a bit of backlog grooming)

**Comment by aalves08** [comment] 2024-07-12 11:57
No more feedback after a long time. Closing this issue.

**Closed by aalves08** 2024-07-12 11:57 UTC
