### ISSUE TITLE
Errormessage `querySelector` is not a function

### ISSUE THREAD

**Issue by mpas** [rancher/elemental-ui#125] opened 2023-06-30 05:18 UTC
Getting the following error on a new cluster using the elemental ui. It does not let me navigate anymore to the Dashboard.

- Created a machine registration endpoint

![image](https://github.com/rancher/elemental-ui/assets/139094/b190113e-3f73-4491-81af-dd2d12380de3)

- Navigating to the Dashboard URL

![image](https://github.com/rancher/elemental-ui/assets/139094/ff8d8ca8-3dd4-47f7-a9f3-9b9b36084490)

**Comment by agracey** [comment] 2023-06-30 14:11
Which versions of Rancher, Elemental Operator, and Elemental Extension are you using?

**Comment by aalves08** [comment] 2024-11-29 11:36
Closing this issue as I can reproduce it and new versions of Elemental have since been released without mentioning this issue

**Closed by aalves08** 2024-11-29 11:36 UTC
Labels: bug
